export enum ROUTES {
  SIGN_IN = "/sign-in",
  SIGN_UP = "/sign-up",
  SIGN_UP_DEVELOPER = "/sign-up-developer",
  HOME_PAGE = "/",
  NFT_PAGE = "/nft-page",
  GAMES_PAGE = "/games-page",
  FORGOT_PASSWORD = "/forgot-password",
  VERIFY_EMAIL = "/verify-email",
  OOPS_PAGE = "/oops",
  GAME_PAGE = "/game-page",
  MARKETPLACE_PAGE = "/marketplace-page",
  CHAT_PAGE = "/chat-page",
  FRIENDS_PAGE = "/friends-page",
  GUILD_PAGE = "/guild-page",
  CURRENT_PROFILE_PAGE = "/me",
  PROFILE_PAGE = "/user/:userId",
  DEVELOPER_PAGE = "/developer-page",
  DEVELOPER_PAGE_CREATE_NFT_PAGE = "/developer-page/create-nft-page",
  DEVELOPER_PAGE_SELLER_PAGE = "/developer-page/seller-page",
  DEVELOPER_PAGE_CONNECT_GAME_PAGE = "/developer-page/new-game-page",
  NOT_FOUND = "/not-found",
}
